# Generated by Django 5.2.5 on 2025-08-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_phone_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a detailed description of the product', null=True),
        ),
    ]
